### ISSUE TITLE
Symbol library cache file is missing

### ISSUE THREAD

**Issue by nikitalita** [raptorlightning/I2SHat#1]
![image](https://user-images.githubusercontent.com/69168929/173723808-ff4fdd53-4bc4-4ec2-b7af-87cbefe63d34.png)

This means there are a lot of missing symbols in the schematic, like so: 
![image](https://user-images.githubusercontent.com/69168929/173723849-757c34c7-f10a-4d89-b735-0f418ceda98f.png)

**Comment by raptorlightning** [comment]
Uploaded symbol cache, thanks!
